version: 2
jobs:
  build-and-test:
    workind_directory: ~/ceos-sls

    docker:
      # specify the version you desire here
      - image: circleci/node:6.10

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            - dependencies-cache

      run:
        name: Install Serverless CLI and dependencies
        command: |
          sudo npm i -g serverless
          npm install

      run:
        name: run tests with code coverage
        command: npm test --coverage

      run:
        name: Deploy app
        command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
