version: 2
jobs:
  build:
    workind_directory: ~/ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

  test:
    workind_directory: ~/ceos-sls
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: run tests with code coverage
          command: yarn test --coverage

  deploy:
    workind_directory: ~/ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - run:
          name: Deploy app
          command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
        requires:
          - test
#        filters:
#          branches:
#            only: master


