version: 2
jobs:
  build:
    working_directory: ~/ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package-lock.json" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
            ls
            echo "test"
            ls -a ~
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: node_modules

  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/node_modules
      - run:
          name: run tests with code coverage
#          command: npm test --coverage
          command: |
            ls
            echo "test"
            ls -a ~
            npm test --coverage

  deploy:
    workind_directory: ~/ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - run:
          name: Deploy app
          command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
#        filters:
#          branches:
#            only: master


