version: 2
jobs:
  build:
    working_directory: ~/v2ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          key: v2ceos-sls-{{ checksum "package-lock.json" }}

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
            sudo mv /usr/local/lib/node_modules/serverless ./node_modules
      - save_cache:
          key: v2ceos-sls-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  test:
    working_directory: ~/v2ceos-sls

    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          key: v2ceos-sls-{{ checksum "package-lock.json" }}

      - run:
          name: run tests with code coverage
          command: |
            npm test --coverage

  deploy:
    working_directory: ~/v2ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - restore_cache:
            key: v2ceos-sls-{{ checksum "package-lock.json" }}

      - run:
          name: logs
          command: |
            cd node_modules
            ls
            ls | grep serverless
      - run:
          name: Deploy app
          command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
#        filters:
#          branches:
#            only: master


