version: 2
jobs:
  build:
    working_directory: ~/ceos-sls

    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          key:
            -v1-{{ checksum "package-lock.json" }}
#            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            npm install
            npm i serverless
            echo "test"
            npm root -g
      - save_cache:
          key:
            -v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - /usr/local/lib/node_modules/serverless

#      - persist_to_workspace:
#          root: /home/circleci
#          paths:
#            -

  test:
    working_directory: ~/ceos-sls

    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          key: -v1-{{ checksum "package-lock.json" }}
#      - attach_workspace:
#          at: /tmp/node_modules
      - run:
          name: run tests with code coverage
#          command: npm test --coverage
          command: |
            pwd
            ls
            echo "test"
            ls -a ~
            npm test --coverage

  deploy:
    working_directory: ~/ceos-sls


    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - restore_cache:
            key: -v1-{{ checksum "package-lock.json" }}
      - run:
          name: Logs
          command: |
            cd node_modules
            ls
            echo "mama"
      - run:
          name: Deploy app
          command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
#        filters:
#          branches:
#            only: master


